# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91f8581eeeca871c9d360ecf2b452bb76cccffb45392f3af633bfa56f833044d829050ea1f29541aecaa99f90be0bae13a5eb6c29160570eca78ed885b721359

test:
  secret_key_base: 306bb4b4232c83c382e9f7994fa99c150937348db2c1d22eb9a4a6ed6a6dd29a9901ba712b48cd86a06070e165242830e326a8231693d0bf4b08358669c732ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
